services:
  webapplication:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    ports:
      - "8080:8080"
    volumes:
      - webapplication:/app
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - postgres

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  postgres:
    image: "postgres:13"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "your_database"
    ports:
      - "5432:5432"

volumes:
  webapplication: